In [1]:
install.packages(c("tidyverse", "jsonlite", "readxl", "writexl", "RSQLite", "DBI", "lubridate"))

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
library(tidyverse)
library(jsonlite)
library(readxl)
library(writexl)
library(RSQLite)
library(DBI)
library(lubridate)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten

In [3]:
data <- read_excel("data.xlsx")

head(data)

  InvoiceNo StockCode Description                         Quantity
1 536365    85123A    WHITE HANGING HEART T-LIGHT HOLDER  6
2 536365    71053     WHITE METAL LANTERN                 6
3 536365    84406B    CREAM CUPID HEARTS COAT HANGER      8
4 536365    84029G    KNITTED UNION FLAG HOT WATER BOTTLE 6
5 536365    84029E    RED WOOLLY HOTTIE WHITE HEART.      6
6 536365    22752     SET 7 BABUSHKA NESTING BOXES        2
  InvoiceDate         UnitPrice CustomerID Country
1 2010-12-01 08:26:00 2.55      17850      United Kingdom
2 2010-12-01 08:26:00 3.39      17850      United Kingdom
3 2010-12-01 08:26:00 2.75      17850      United Kingdom
4 2010-12-01 08:26:00 3.39      17850      United Kingdom
5 2010-12-01 08:26:00 3.39      17850      United Kingdom
6 2010-12-01 08:26:00 7.65      17850      United Kingdom

In [4]:
transactions <- data %>%
  select(
    InvoiceNo,
    StockCode,
    CustomerID,
    Quantity,
    InvoiceDate
  )
head(transactions)
write_csv(transactions, "transactions.csv")

  InvoiceNo StockCode CustomerID Quantity InvoiceDate
1 536365    85123A    17850      6        2010-12-01 08:26:00
2 536365    71053     17850      6        2010-12-01 08:26:00
3 536365    84406B    17850      8        2010-12-01 08:26:00
4 536365    84029G    17850      6        2010-12-01 08:26:00
5 536365    84029E    17850      6        2010-12-01 08:26:00
6 536365    22752     17850      2        2010-12-01 08:26:00

In [5]:
products <- data %>%
  select(
    StockCode,
    Description,
    UnitPrice
  ) %>%
  distinct()
head(products)
write_json(
  products,
  "products.json",
  pretty = TRUE,
  auto_unbox = TRUE
)

  StockCode Description                         UnitPrice
1 85123A    WHITE HANGING HEART T-LIGHT HOLDER  2.55
2 71053     WHITE METAL LANTERN                 3.39
3 84406B    CREAM CUPID HEARTS COAT HANGER      2.75
4 84029G    KNITTED UNION FLAG HOT WATER BOTTLE 3.39
5 84029E    RED WOOLLY HOTTIE WHITE HEART.      3.39
6 22752     SET 7 BABUSHKA NESTING BOXES        7.65

In [6]:
customers <- data %>%
  select(
    CustomerID,
    Country
  ) %>%
  distinct()
head(customers)
write_xlsx(
  customers,
  "customers.xlsx"
)

  CustomerID Country
1 17850      United Kingdom
2 13047      United Kingdom
3 12583      France
4 13748      United Kingdom
5 15100      United Kingdom
6 15291      United Kingdom

In [7]:
transactions <- read_csv("transactions.csv")

products <- fromJSON("products.json") %>%
  as.data.frame()

customers <- read_excel("customers.xlsx")

head(transactions)
head(products)
head(customers)

Rows: 541909 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): InvoiceNo, StockCode
dbl  (2): CustomerID, Quantity
dttm (1): InvoiceDate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  InvoiceNo StockCode CustomerID Quantity InvoiceDate
1 536365    85123A    17850      6        2010-12-01 08:26:00
2 536365    71053     17850      6        2010-12-01 08:26:00
3 536365    84406B    17850      8        2010-12-01 08:26:00
4 536365    84029G    17850      6        2010-12-01 08:26:00
5 536365    84029E    17850      6        2010-12-01 08:26:00
6 536365    22752     17850      2        2010-12-01 08:26:00

  StockCode Description                         UnitPrice
1 85123A    WHITE HANGING HEART T-LIGHT HOLDER  2.55
2 71053     WHITE METAL LANTERN                 3.39
3 84406B    CREAM CUPID HEARTS COAT HANGER      2.75
4 84029G    KNITTED UNION FLAG HOT WATER BOTTLE 3.39
5 84029E    RED WOOLLY HOTTIE WHITE HEART.      3.39
6 22752     SET 7 BABUSHKA NESTING BOXES        7.65

  CustomerID Country
1 17850      United Kingdom
2 13047      United Kingdom
3 12583      France
4 13748      United Kingdom
5 15100      United Kingdom
6 15291      United Kingdom

In [8]:
cat("Transactions:", nrow(transactions), "rows,", ncol(transactions), "columns\n")
cat("Products:", nrow(products), "rows,", ncol(products), "columns\n")
cat("Customers:", nrow(customers), "rows,", ncol(customers), "columns\n")

Transactions: 541909 rows, 5 columns
Products: 18044 rows, 3 columns
Customers: 4389 rows, 2 columns

In [9]:
cat("Missing values in Transactions:\n")
print(colSums(is.na(transactions)))
cat("\nMissing values in Products:\n")
print(colSums(is.na(products)))
cat("\nMissing values in Customers:\n")
print(colSums(is.na(customers)))

Missing values in Transactions:
  InvoiceNo   StockCode  CustomerID    Quantity InvoiceDate
          0           0      135080           0           0

Missing values in Products:
  StockCode Description   UnitPrice
          0         960           0

Missing values in Customers:
CustomerID    Country
         9          0

In [10]:
cat("Duplicate transactions:", sum(duplicated(transactions)), "\n")
cat("Duplicate products:", sum(duplicated(products)), "\n")
cat("Duplicate customers:", sum(duplicated(customers)), "\n")

Duplicate transactions: 5429
Duplicate products: 0
Duplicate customers: 0

In [11]:
cat(
  "Products with UnitPrice <= 0:",
  sum(products$UnitPrice <= 0, na.rm = TRUE),
  "\n"
)

Products with UnitPrice <= 0: 1771

In [12]:
cat(
  "Transactions with Quantity <= 0:",
  sum(transactions$Quantity <= 0, na.rm = TRUE),
  "\n"
)

Transactions with Quantity <= 0: 10624

In [13]:
transactions_clean <- transactions %>%
  distinct() %>%
  filter(
    !is.na(InvoiceNo),
    !is.na(StockCode),
    !is.na(CustomerID),
    !is.na(Quantity),
    !is.na(InvoiceDate),
    Quantity > 0
  )

cat("Rows before cleaning:", nrow(transactions), "\n")
cat("Rows after cleaning:", nrow(transactions_clean), "\n")

Rows before cleaning: 541909
Rows after cleaning: 392708

In [14]:
products_clean <- products %>%
  filter(
    !is.na(StockCode),
    !is.na(Description),
    !is.na(UnitPrice),
    UnitPrice > 0
  ) %>%
  group_by(StockCode) %>%
  summarise(
    Description = first(Description),
    UnitPrice = first(UnitPrice),
    .groups = "drop"
  )
cat("Unique product records:", nrow(products_clean), "\n")

Unique product records: 3938

In [15]:
customers_clean <- customers %>%
  filter(
    !is.na(CustomerID),
    !is.na(Country)
  ) %>%
  group_by(CustomerID) %>%
  summarise(
    Country = first(Country),
    .groups = "drop"
  )

cat("Rows before cleaning:", nrow(customers), "\n")
cat("Rows after cleaning:", nrow(customers_clean), "\n")

Rows before cleaning: 4389
Rows after cleaning: 4372

In [16]:
transactions_clean <- transactions_clean %>%
  mutate(
    StockCode = as.character(StockCode),
    CustomerID = as.character(CustomerID),
    Quantity = as.numeric(Quantity),
    InvoiceDate = as.character(InvoiceDate)
  )
products_clean <- products_clean %>%
  mutate(
    StockCode = as.character(StockCode),
    UnitPrice = as.numeric(UnitPrice)
  )
customers_clean <- customers_clean %>%
  mutate(
    CustomerID = as.character(CustomerID)
  )

In [17]:
transactions_products <- transactions_clean %>%
  left_join(
    products_clean,
    by = "StockCode"
  ) %>%
  mutate(
    Revenue = Quantity * UnitPrice
  )

In [18]:
summary(transactions_clean)
summary(products_clean)
summary(customers_clean)
cat("\nFinal transaction rows:", nrow(transactions_clean))
cat("\nFinal product rows:", nrow(products_clean))
cat("\nFinal customer rows:", nrow(customers_clean))

     InvoiceNo          StockCode          CustomerID        Quantity
 Length   :392708   Length   :392708   Length   :392708   Min.   :    1.00
 N.unique : 18536   N.unique :  3665   N.unique :  4339   1st Qu.:    2.00
 N.blank  :     0   N.blank  :     0   N.blank  :     0   Median :    6.00
 Min.nchar:     6   Min.nchar:     1   Min.nchar:     5   Mean   :   13.15
 Max.nchar:     6   Max.nchar:    12   Max.nchar:     5   3rd Qu.:   12.00
                                                          Max.   :80995.00
    InvoiceDate
 Length   :392708
 N.unique : 17286
 N.blank  :     0
 Min.nchar:    19
 Max.nchar:    19

     StockCode       Description     UnitPrice
 Length   :3938   Length   :3938   Min.   :    0.001
 N.unique :3938   N.unique :3803   1st Qu.:    1.250
 N.blank  :   0   N.blank  :   0   Median :    2.510
 Min.nchar:   1   Min.nchar:   6   Mean   :    7.229
 Max.nchar:  12   Max.nchar:  35   3rd Qu.:    4.950
                                   Max.   :11062.060

     CustomerID        Country
 Length   :4372   Length   :4372
 N.unique :4372   N.unique :  37
 N.blank  :   0   N.blank  :   0
 Min.nchar:   5   Min.nchar:   3
 Max.nchar:   5   Max.nchar:  20

Final transaction rows: 392708
Final product rows: 3938
Final customer rows: 4372

### Cleaning Decisions

1. Duplicate transaction records were removed.
2. Transactions with missing essential fields were removed.
3. Transactions with quantity less than or equal to zero were removed.
4. Products with missing StockCode, Description or UnitPrice were removed.
5. Products with UnitPrice less than or equal to zero were removed.
6. Product records were reduced to one record per StockCode for reliable joining.
7. Customers with missing CustomerID or Country were removed.
8. Customer records were reduced to one record per CustomerID for reliable joining.
9. Revenue was calculated as Quantity × UnitPrice.

In [19]:
final_data <- transactions_products %>%
  left_join(
    customers_clean,
    by = "CustomerID"
  )

cat("Transactions:", nrow(transactions_clean), "\n")
cat("Final integrated dataset:", nrow(final_data), "\n")

Transactions: 392708
Final integrated dataset: 392708

In [20]:
cat("Final dataset dimensions:\n")
cat("Rows:", nrow(final_data), "\n")
cat("Columns:", ncol(final_data), "\n")

Final dataset dimensions:
Rows: 392708
Columns: 9

In [21]:
unmatched_products <- final_data %>%
  filter(is.na(Description))
cat(
  "Unmatched product records:",
  nrow(unmatched_products),
  "\n"
)

Unmatched product records: 0

In [22]:
unmatched_customers <- final_data %>%
  filter(is.na(Country))
cat(
  "Unmatched customer records:",
  nrow(unmatched_customers),
  "\n"
)

Unmatched customer records: 0

In [23]:
cat("Transactions:", nrow(transactions_clean), "\n")
cat("Integrated dataset:", nrow(final_data), "\n")
cat(
  "Difference:",
  nrow(final_data) - nrow(transactions_clean),
  "\n"
)

Transactions: 392708
Integrated dataset: 392708
Difference: 0

In [24]:
total_revenue <- final_data %>%
  summarise(
    Total_Revenue = sum(Revenue, na.rm = TRUE)
  )

total_revenue

  Total_Revenue
1 10885988

In [25]:
top_5_products <- final_data %>%
  filter(!is.na(Description)) %>%
  group_by(StockCode, Description) %>%
  summarise(
    Total_Revenue = sum(Revenue, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue)) %>%
  slice_head(n = 5)

top_5_products

  StockCode Description                        Total_Revenue
1 23843     PAPER CRAFT , LITTLE BIRDIE        168469.60
2 47566     PARTY BUNTING                      142437.56
3 22423     REGENCY CAKESTAND 3 TIER           135604.80
4 85123A    WHITE HANGING HEART T-LIGHT HOLDER  93745.65
5 23166     MEDIUM CERAMIC TOP STORAGE JAR      81032.64

In [26]:
top_5_countries <- final_data %>%
  filter(!is.na(Country)) %>%
  group_by(Country) %>%
  summarise(
    Total_Revenue = sum(Revenue, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue)) %>%
  slice_head(n = 5)

top_5_countries

  Country        Total_Revenue
1 United Kingdom 8977081.4
2 Netherlands     367800.5
3 EIRE            333506.1
4 Germany         266796.4
5 France          230786.8

In [27]:
top_5_customers <- final_data %>%
  filter(!is.na(CustomerID)) %>%
  group_by(CustomerID) %>%
  summarise(
    Total_Purchase_Value = sum(Revenue, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Purchase_Value)) %>%
  slice_head(n = 5)

top_5_customers

  CustomerID Total_Purchase_Value
1 18102      408968.0
2 14646      361409.8
3 17450      190700.9
4 14911      184256.0
5 16446      168472.5

In [28]:
customer_value <- final_data %>%
  filter(!is.na(CustomerID)) %>%
  group_by(CustomerID) %>%
  summarise(
    Total_Purchase_Value = sum(Revenue, na.rm = TRUE),
    .groups = "drop"
  )
head(customer_value)

  CustomerID Total_Purchase_Value
1 12346      77183.60
2 12347       5438.44
3 12348       1790.16
4 12349       1957.11
5 12350        408.04
6 12352       1616.57

In [29]:
q1 <- quantile(
  customer_value$Total_Purchase_Value,
  0.25,
  na.rm = TRUE
)
q2 <- quantile(
  customer_value$Total_Purchase_Value,
  0.50,
  na.rm = TRUE
)
q3 <- quantile(
  customer_value$Total_Purchase_Value,
  0.75,
  na.rm = TRUE
)
cat("Low/Medium threshold:", q1, "\n")
cat("Medium/High threshold:", q2, "\n")
cat("High/Premium threshold:", q3, "\n")

Low/Medium threshold: 363.88
Medium/High threshold: 811.32
High/Premium threshold: 2017.485

In [30]:
customer_value <- customer_value %>%
  mutate(
    Customer_Segment = case_when(
      Total_Purchase_Value <= q1 ~ "Low Value",
      Total_Purchase_Value <= q2 ~ "Medium Value",
      Total_Purchase_Value <= q3 ~ "High Value",
      TRUE ~ "Premium"
    )
  )
head(customer_value)

  CustomerID Total_Purchase_Value Customer_Segment
1 12346      77183.60             Premium
2 12347       5438.44             Premium
3 12348       1790.16             High Value
4 12349       1957.11             High Value
5 12350        408.04             Medium Value
6 12352       1616.57             High Value

In [31]:
customer_segments <- customer_value %>%
  count(Customer_Segment)
customer_segments

  Customer_Segment n
1 High Value       1084
2 Low Value        1085
3 Medium Value     1085
4 Premium          1085

In [32]:
segment_revenue <- customer_value %>%
  group_by(Customer_Segment) %>%
  summarise(
    Number_of_Customers = n(),
    Total_Revenue = sum(Total_Purchase_Value),
    Average_Purchase_Value = mean(Total_Purchase_Value),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue))
segment_revenue

  Customer_Segment Number_of_Customers Total_Revenue Average_Purchase_Value
1 Premium          1085                8630924.6     7954.7692
2 High Value       1084                1415683.5     1305.9811
3 Medium Value     1085                 608029.4      560.3957
4 Low Value        1085                 231350.6      213.2264

In [33]:
country_performance <- final_data %>%
  filter(!is.na(Country)) %>%
  group_by(Country) %>%
  summarise(
    Total_Revenue = sum(Revenue, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(Total_Revenue))

country_performance

   Country              Total_Revenue
1  United Kingdom       8977081.38
2  Netherlands           367800.49
3  EIRE                  333506.07
4  Germany               266796.43
5  France                230786.84
6  Australia             175628.20
7  Spain                  67593.96
8  Switzerland            67487.88
9  Japan                  48600.22
10 Belgium                48377.42
11 Sweden                 43706.57
12 Norway                 40318.00
13 Portugal               33375.75
14 Finland                23674.05
15 Channel Islands        22227.32
16 Denmark                21352.84
17 Italy                  21193.14
18 Cyprus                 17028.52
19 Singapore              11620.38
20 Poland                 10294.39
21 Austria                 9912.71
22 Israel                  9146.89
23 Greece                  6128.80
24 Iceland                 5438.44
25 Canada                  4315.90
26 USA                     4171.83
27 Unspecified             2955.20
28 Malta                   2890.34
29 United Arab Emirates    2747.72
30 Lebanon                 2085.13
31 Lithuania               1867.34
32 European Community      1575.65
33 Brazil                  1225.35
34 RSA                     1152.51
35 Czech Republic          1026.26
36 Bahrain                  716.78
37 Saudi Arabia             181.44

In [34]:
high_performing_market <- country_performance %>%
  slice_max(
    order_by = Total_Revenue,
    n = 1
  )
high_performing_market

  Country        Total_Revenue
1 United Kingdom 8977081

In [35]:
underperforming_market <- country_performance %>%
  slice_min(
    order_by = Total_Revenue,
    n = 1
  )
underperforming_market

  Country      Total_Revenue
1 Saudi Arabia 181.44

In [36]:
cat("===== SALES ANALYSIS SUMMARY =====\n\n")

cat(
  "Total Revenue:",
  round(total_revenue$Total_Revenue, 2),
  "\n\n"
)

cat("Top 5 Products:\n")
print(top_5_products)

cat("\nTop 5 Countries:\n")
print(top_5_countries)

cat("\nTop 5 Customers:\n")
print(top_5_customers)

cat("\nCustomer Segments:\n")
print(segment_revenue)

cat("\nHigh-Performing Market:\n")
print(high_performing_market)

cat("\nUnderperforming Market:\n")
print(underperforming_market)

===== SALES ANALYSIS SUMMARY =====

Total Revenue: 10885988

Top 5 Products:
# A tibble: 5 × 3
  StockCode Description                        Total_Revenue
  <chr>     <chr>                                      <dbl>
1 23843     PAPER CRAFT , LITTLE BIRDIE              168470.
2 47566     PARTY BUNTING                            142438.
3 22423     REGENCY CAKESTAND 3 TIER                 135605.
4 85123A    WHITE HANGING HEART T-LIGHT HOLDER        93746.
5 23166     MEDIUM CERAMIC TOP STORAGE JAR            81033.

Top 5 Countries:
# A tibble: 5 × 2
  Country        Total_Revenue
  <chr>                  <dbl>
1 United Kingdom      8977081.
2 Netherlands          367800.
3 EIRE                 333506.
4 Germany              266796.
5 France               230787.

Top 5 Customers:
# A tibble: 5 × 2
  CustomerID Total_Purchase_Value
  <chr>                     <dbl>
1 18102                   408968.
2 14646                   361410.
3 17450                   190701.
4 14911                   184256.
5 16446                   168472.

Customer Segments:
# A tibble: 4 × 4
  Customer_Segment Number_of_Customers Total_Revenue Average_Purchase_Value
  <chr>                          <int>         <dbl>                  <dbl>
1 Premium                         1085      8630925.                  7955.
2 High Value                      1084      1415684.                  1306.
3 Medium Value                    1085       608029.                   560.
4 Low Value                       1085       231351.                   213.

High-Performing Market:
# A tibble: 1 × 2
  Country        Total_Revenue
  <chr>                  <dbl>
1 United Kingdom      8977081.

Underperforming Market:
# A tibble: 1 × 2
  Country      Total_Revenue
  <chr>                <dbl>
1 Saudi Arabia          181.

In [37]:
con <- dbConnect(
  SQLite(),
  "retail_sales.db"
)

In [38]:
dbWriteTable(
  con,
  "retail_sales",
  final_data,
  overwrite = TRUE
)

In [39]:
dbListFields(con, "retail_sales")

[1] "InvoiceNo"   "StockCode"   "CustomerID"  "Quantity"    "InvoiceDate"
[6] "Description" "UnitPrice"   "Revenue"     "Country"

In [40]:
query1 <- "
SELECT
    CustomerID,
    SUM(Revenue) AS Total_Revenue
FROM retail_sales
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY Total_Revenue DESC
LIMIT 5;
"

top_5_customers_sql <- dbGetQuery(con, query1)

top_5_customers_sql

  CustomerID Total_Revenue
1 18102      408968.0
2 14646      361409.8
3 17450      190700.9
4 14911      184256.0
5 16446      168472.5

In [41]:
query2 <- "
SELECT
    Country,
    SUM(Revenue) AS Total_Revenue
FROM retail_sales
WHERE Country IS NOT NULL
GROUP BY Country
ORDER BY Total_Revenue DESC;
"

revenue_by_country_sql <- dbGetQuery(con, query2)

head(revenue_by_country_sql, 10)

   Country        Total_Revenue
1  United Kingdom 8977081.38
2  Netherlands     367800.49
3  EIRE            333506.07
4  Germany         266796.43
5  France          230786.84
6  Australia       175628.20
7  Spain            67593.96
8  Switzerland      67487.88
9  Japan            48600.22
10 Belgium          48377.42

In [42]:
dbDisconnect(con)

## Three Business Insights

### 1. United Kingdom is the strongest market
The **United Kingdom** is the highest-performing market, generating total revenue of **8,977,081**. This represents the largest share of the overall revenue of **10,885,988**, indicating that the United Kingdom is the company's primary market.

### 2. Premium customers contribute the majority of revenue
The **Premium** customer segment generated **8,630,925** in revenue from **1,085 customers**, with an average purchase value of approximately **7,955** per customer. This indicates that premium customers make a major contribution to overall revenue and should be prioritized for customer retention and loyalty strategies.

### 3. Certain products and customers contribute significantly to sales
The top-performing product, **PAPER CRAFT , LITTLE BIRDIE (StockCode: 23843)**, generated **168,470** in revenue. The highest-value customer, **Customer 18102**, generated **408,968** in purchases. This shows that specific products and high-value customers contribute significantly to sales and should receive attention in inventory planning, promotions, and customer retention.